In [1]:
import numpy as np
import pandas as pd

In [15]:
a = np.array(([2,3],[5,5]))

In [16]:
a.shape

(2, 2)

In [10]:
np.empty([3,2], dtype=int)

array([[94567739229120,              0],
       [             0,              0],
       [             0,              0]])

In [11]:
np.zeros([3,2])

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [13]:
np.ones([3,2])

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [14]:
x = [1,2,3]
np.asarray(x)

array([1, 2, 3])